# Generated by Django 4.0.5 on 2022-06-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haberler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150)),
                ('anahaber', models.TextField()),
                ('sehir', models.CharField(max_length=150)),
                ('zaman', models.DateField()),
                ('resim', models.CharField(max_length=150)),
            ],
        ),
    ]
